version: '3.3'

services:
  app:
    container_name: app
    build:
      context: .

    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    command: >
      sh -c "
      PGPASSWORD=postgres psql -h localhost -U postgres -w -c 'CREATE DATABASE database;'
      && alembic upgrade head
      && PGPASSWORD=postgres psql -h localhost -U postgres -w -d database -c 'INSERT INTO identifier (telegram_id) VALUES (1234), (1200), (333), (4321);'"
