version: '3.9'

services:
  project_img:
    build:
      context: .
      dockerfile: Dockerfile
    image: telegram_bot_notifire:latest

  project_app:
    image: telegram_bot_notifire:latest
    env_file:
      - .env
    restart: on-failure

  project:
    extends:
      service: project_app
    depends_on:
      - postgres
    command: ./wait-for-it.sh postgres:5432 -- python3 ./main.py
    ports:
      - "8000:8000"

  postgres:
    image: postgres:16
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
