version: '3.3'

services:
  app:
    container_name: app
    build:
      context: .

    ports:
      - "5000:5000"
    depends_on:
      - db
#      - telegram-bot
    restart: on-failure

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .dbenv
#    environment:
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword

#  telegram-bot:
#    image: "python:3.9-slim"
#    volumes:
#      - ./app:/app
#    command: python telegram_bot.py
#    environment:
#      TELEGRAM_BOT_TOKEN: "your_bot_token"
