version: '3.3'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure
    command: sh -c "./wait-for-it.sh postgres:5432 -- python3 ./main.py"

  postgres:
    image: postgres:16
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
